# TODO: this doesn't work yet

name: summary_stats_env

channels:
  - conda-forge
  - jaredgk
  - bioconda
dependencies:
  - python==3.7.12
  - py-popgen==0.1.12
  - plink2==2.00a5
  - admixture==1.3.0
  - gsl==2.7.1
  - pandas-plink==2.2.9
  - seaborn==0.12.2 
  - plink==1.90b6.21
  - pixy==1.2.7.beta1
  - htslib==1.3.1 
  - admixtools==7.0.2
